<?php
require_once __DIR__ . '/config.php';

ob_start();
set_error_handler(function ($severity, $message, $file, $line) {
    throw new ErrorException($message, 0, $severity, $file, $line);
});

function fail_json(int $status, string $message): void
{
    if (ob_get_length()) ob_clean();
    http_response_code($status);
    echo json_encode(["error" => $message]);
    exit;
}

$data = json_decode(file_get_contents('php://input'), true);
if (!$data) {
    fail_json(400, "Invalid JSON");
}

$first = $conn->real_escape_string($data['first_name'] ?? '');
$last = $conn->real_escape_string($data['last_name'] ?? '');
$email = $conn->real_escape_string($data['email'] ?? '');
$dept = $conn->real_escape_string($data['dept'] ?? '');
$designation = $conn->real_escape_string($data['designation'] ?? '');

if (!$first || !$last || !$email || !$designation) {
    fail_json(400, "Missing required fields");
}
// Prevent duplicate email
$email_check = $conn->prepare("SELECT 1 FROM user WHERE `E-mail` = ? LIMIT 1");
if (!$email_check) fail_json(500, "Prepare email check failed: " . $conn->error);
$email_check->bind_param('s', $email);
$email_check->execute();
$email_check->store_result();
if ($email_check->num_rows > 0) {
    $email_check->close();
    fail_json(409, "A user with this email already exists.");
}
$email_check->close();

// Note: Faculty_id is generated by the DB as AUTO_INCREMENT. Do not accept from client.

try {
    $conn->begin_transaction();

    // Insert into user
    $stmt = $conn->prepare("INSERT INTO user (First_Name, Last_Name, `E-mail`, Dept, Is_guest) VALUES (?, ?, ?, ?, 0)");
    if (!$stmt) throw new RuntimeException("Prepare user insert failed: " . $conn->error);
    $stmt->bind_param('ssss', $first, $last, $email, $dept);
    if (!$stmt->execute()) throw new RuntimeException("Insert user failed: " . $stmt->error);
    $user_id = $conn->insert_id;
    $stmt->close();

    // Insert into faculty; DB must have Faculty_id as AUTO_INCREMENT
    $is_active = 1;
    $stmt2 = $conn->prepare("INSERT INTO faculty (User_id, Designation, Is_active) VALUES (?, ?, ?)");
    if (!$stmt2) throw new RuntimeException("Prepare faculty insert failed: " . $conn->error);
    $stmt2->bind_param('isi', $user_id, $designation, $is_active);
    if (!$stmt2->execute()) throw new RuntimeException("Insert faculty failed: " . $stmt2->error);
    $stmt2->close();

    $conn->commit();
    if (ob_get_length()) ob_clean();
    echo json_encode(["success" => true, "user_id" => $user_id]);
} catch (Throwable $e) {
    if ($conn->errno) $conn->rollback();
    fail_json(500, $e->getMessage());
}
